### PR TITLE
Defunc unprefixed pstr data

### PR DESCRIPTION
**Pull request by maurolepore**
This PR removes pstr datasets which name lacks the "pstr_" prefix.

Now the API is more consistent and plays well with autocomplete.

This is a breaking changes and thus requires review to ensure
we abandon the old names and use the new names everywhere.

### CODE REVIEW

**Review by lindadelacombaz — COMMENTED** [review]
Nice. So I think the documentation of the functions also need to be changed ? for example, the return description of pstr_add_reductions()  still has the old name of the data sets.

**Comment by maurolepore** [comment]
Yes, good catch. I'll have another look but if you already saw something using the old name please point it to me.

**Comment by lindadelacombaz** [comment]
I just checked, I saw them only in the documentation in every pstr_ functions and also test-pstr_data.R (test_that("`companies`) hasn't changed" --> (test_that("`pstr_companies`) hasn't changed" )

Otherwise I think it's good !

**Review by maurolepore — COMMENTED** [review]
I didn't add the prefix to function arguments, which means I also didn't change the reference to those arguments in `@return`. I'm not 100% sure it's the best approach but I lean towards thinking that the prefix in the function name is enough context and thus the prefix in the arguments would be a little redundant -- adding maintenance cost with no additional value. Once the user found a function (maybe with the help of auto-complete) it should be clear the sope of those arguments is the one provided by the function.

I think the prefix is best limited to interfaces (function and datasets names) and it we carry them to the arguments, they "leak" an interface detail into the implementation details of the function (i.e. the body of the function would use the prefix). This feels odd and as it breaks the isolation that the interface provides. The reason I'm unsure is because all books talk about the dangers of leaking implementation details -- not about the dangers of leaking interface details -- but it rings to me that both are cases of the more general problem of breaking the insulation between that an interface provides between what happens outside and inside the interface.

**Review by lindadelacombaz — APPROVED** [review]
LGTM ! :)

**Pull request merged**
